language: node_js
node_js:
- '6.5'
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
- rvm install `cat .ruby-version`
- gem install bundler
install:
- npm install
script:
- npm run-script build
after_success:
- npm run-script deploy
env:
- CXX=g++-4.8 AWS_S3_BUCKET=s3.fightforthefuture.org AWS_S3_FOLDER=images/blog ACTIONNETWORK_URL=https://actionnetwork.org
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  only:
  - production
deploy:
  provider: s3
  access_key_id: AKIAJBUMOKIYAH4JO5FQ
  secret_access_key:
    secure: b2QaR+6fuC6HD6iK4ABJtcFkYtnk9BhJ7R9uWgQVYtx6U6Y2fw3MqpFCywpyhsO0TY2c3M2K/wYyXE765aOBWEJpByK3AW1vSLlUZNJICBtraXSbAoyxCnTVd1wYAwAi2CR1EuvrTGXNynCt3X0SoyWwrQbUSMvO27T7ZVmVG4U=
  bucket: s3.fightforthefuture.org
  local-dir: assets
  acl: public_read
  skip_cleanup: true
  cache_control: "max-age=41706360"
  on:
    repo: fightforthefuture/fightforthefuture.github.io
    branch: production
